[package]
name = "combinators"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
directories = "5.0.1"
extism = "1.0.0"
serde = "1.0.195"
termsize = "0.1.6"
